In [30]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
!pip install nashpy
import nashpy as nash


In [31]:
set_C= pd.read_csv("data.csv", sep=";", header=None)

In [32]:
set_C.columns=["A1","A2", "A3", "A4","Objects"]
set_C=set_C.set_index('Objects')


In [33]:
df_U= pd.read_csv("data_U.csv", sep=";", header=None)
df_U.columns=["A1","A2", "A3", "A4","Objects"]
df_U=df_U.set_index('Objects')
df_U

A1   A2   A3   A4
Objects                    
o1       5,9  3,2  4,8    2
o2       6,1  2,8  4,2  1,5
o3       6,4  2,8  4,6  1,3
o4       6,4  2,5  4,3  1,4
o5       6,3  2,3  4,4  1,5
o6       6,3  2,8  4,9  1,6
o7       5,5  2,4  3,8  1,3
o8       5,8  2,7    4  1,4
o9       5,5  2,4  3,7  1,2
o10        6  2,8  4,5  1,4
o11      5,6  2,9  4,1  1,5
o12      5,5  2,5    4  1,5
o13      5,5  2,6  4,4  1,4
o14      6,1  2,7  4,6  1,4
o15      5,8  2,6    4  1,4
o16      5,8  2,7  5,1  1,9
o17      5,7  2,5    5    2
o18      6,1  2,8  5,6  2,2
o19        6  2,2    5  1,5
o20      5,6  2,8  4,9    2
o21      6,3  2,7  4,9  1,8
o22      6,2  2,8  4,8  1,8
o23      5,9    3  5,1  1,8
o24      6,4  2,8  5,6  2,1
o25      6,5    3  5,5  1,8
o26      6,3  2,8  5,1  1,5
o27      6,1  2,7  5,6  1,5
o28      6,4  3,1  5,5  1,8
o29        6  2,9  4,8  1,6
o30      5,9    3  5,1  1,8
o31      5,5  NaN  3,1  2,5
o32      4,2  3,1  NaN  NaN
o33      NaN    3  2,1  NaN
o34        6  2,2    3  NaN
o35      6,3  NaN    5    1
o36      4,1    4  NaN    6
o37      NaN  NaN  4,8    5
o38        5  1,6  NaN  NaN
o39        2  1,2  6,9  NaN
o40      1,8  NaN    5  3,2

In [34]:
set_M = df_U[df_U.isnull().values.any(axis=1)]
set_M

A1   A2   A3   A4
Objects                    
o31      5,5  NaN  3,1  2,5
o32      4,2  3,1  NaN  NaN
o33      NaN    3  2,1  NaN
o34        6  2,2    3  NaN
o35      6,3  NaN    5    1
o36      4,1    4  NaN    6
o37      NaN  NaN  4,8    5
o38        5  1,6  NaN  NaN
o39        2  1,2  6,9  NaN
o40      1,8  NaN    5  3,2

In [35]:
set_C=df_U[~df_U.isnull().values.any(axis=1)]
set_CU=df_U[~df_U.isnull().values.any(axis=1)]
set_C

A1   A2   A3   A4
Objects                    
o1       5,9  3,2  4,8    2
o2       6,1  2,8  4,2  1,5
o3       6,4  2,8  4,6  1,3
o4       6,4  2,5  4,3  1,4
o5       6,3  2,3  4,4  1,5
o6       6,3  2,8  4,9  1,6
o7       5,5  2,4  3,8  1,3
o8       5,8  2,7    4  1,4
o9       5,5  2,4  3,7  1,2
o10        6  2,8  4,5  1,4
o11      5,6  2,9  4,1  1,5
o12      5,5  2,5    4  1,5
o13      5,5  2,6  4,4  1,4
o14      6,1  2,7  4,6  1,4
o15      5,8  2,6    4  1,4
o16      5,8  2,7  5,1  1,9
o17      5,7  2,5    5    2
o18      6,1  2,8  5,6  2,2
o19        6  2,2    5  1,5
o20      5,6  2,8  4,9    2
o21      6,3  2,7  4,9  1,8
o22      6,2  2,8  4,8  1,8
o23      5,9    3  5,1  1,8
o24      6,4  2,8  5,6  2,1
o25      6,5    3  5,5  1,8
o26      6,3  2,8  5,1  1,5
o27      6,1  2,7  5,6  1,5
o28      6,4  3,1  5,5  1,8
o29        6  2,9  4,8  1,6
o30      5,9    3  5,1  1,8

In [36]:
set_U_no_null=df_U[~df_U.isnull().values.any(axis=1)]

In [37]:
set_C["A1"][0]

'5,9'

In [38]:
set_C[["A1","A2", "A3", "A4"]] = set_C[["A1","A2", "A3", "A4"]].replace(',','.', regex=True).astype(float)
km = KMeans(n_clusters=2)
kmeans = km.fit(set_C)

C:\Users\houss\anaconda3\lib\site-packages\pandas\core\frame.py:3191: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [39]:
cluster_map = pd.DataFrame()
cluster_map['data_index'] = set_C.index.values
cluster_map['A1'] = set_C["A1"].values
cluster_map['A2'] = set_C["A2"].values
cluster_map['A3'] = set_C["A3"].values
cluster_map['A4'] = set_C["A4"].values
cluster_map['cluster'] = kmeans.labels_
cluster_map

data_index   A1   A2   A3   A4  cluster
0          o1  5.9  3.2  4.8  2.0        1
1          o2  6.1  2.8  4.2  1.5        0
2          o3  6.4  2.8  4.6  1.3        0
3          o4  6.4  2.5  4.3  1.4        0
4          o5  6.3  2.3  4.4  1.5        0
5          o6  6.3  2.8  4.9  1.6        1
6          o7  5.5  2.4  3.8  1.3        0
7          o8  5.8  2.7  4.0  1.4        0
8          o9  5.5  2.4  3.7  1.2        0
9         o10  6.0  2.8  4.5  1.4        0
10        o11  5.6  2.9  4.1  1.5        0
11        o12  5.5  2.5  4.0  1.5        0
12        o13  5.5  2.6  4.4  1.4        0
13        o14  6.1  2.7  4.6  1.4        0
14        o15  5.8  2.6  4.0  1.4        0
15        o16  5.8  2.7  5.1  1.9        1
16        o17  5.7  2.5  5.0  2.0        1
17        o18  6.1  2.8  5.6  2.2        1
18        o19  6.0  2.2  5.0  1.5        1
19        o20  5.6  2.8  4.9  2.0        1
20        o21  6.3  2.7  4.9  1.8        1
21        o22  6.2  2.8  4.8  1.8        1
22        o23  5.9  3.0  5.1  1.8        1
23        o24  6.4  2.8  5.6  2.1        1
24        o25  6.5  3.0  5.5  1.8        1
25        o26  6.3  2.8  5.1  1.5        1
26        o27  6.1  2.7  5.6  1.5        1
27        o28  6.4  3.1  5.5  1.8        1
28        o29  6.0  2.9  4.8  1.6        1
29        o30  5.9  3.0  5.1  1.8        1

In [40]:
for col in set_C:
            col_missing_rate = df_U[col].isna().mean()
            vals_to_nan = set_C[col].dropna().sample(frac=col_missing_rate).index
            set_C.loc[vals_to_nan, col] = np.NaN
set_C

C:\Users\houss\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\houss\anaconda3\lib\site-packages\pandas\core\indexing.py:692: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


A1   A2   A3   A4
Objects                    
o1       5.9  3.2  4.8  2.0
o2       6.1  2.8  4.2  1.5
o3       6.4  NaN  NaN  1.3
o4       6.4  2.5  4.3  1.4
o5       6.3  2.3  4.4  1.5
o6       6.3  2.8  4.9  NaN
o7       5.5  2.4  3.8  NaN
o8       NaN  2.7  4.0  1.4
o9       5.5  NaN  NaN  1.2
o10      6.0  2.8  4.5  1.4
o11      5.6  2.9  4.1  1.5
o12      5.5  2.5  4.0  1.5
o13      5.5  NaN  4.4  1.4
o14      6.1  2.7  4.6  1.4
o15      5.8  2.6  4.0  1.4
o16      5.8  2.7  5.1  1.9
o17      5.7  2.5  5.0  2.0
o18      NaN  2.8  5.6  2.2
o19      6.0  2.2  5.0  1.5
o20      5.6  2.8  4.9  2.0
o21      6.3  2.7  4.9  1.8
o22      6.2  2.8  4.8  1.8
o23      5.9  3.0  5.1  1.8
o24      6.4  2.8  5.6  2.1
o25      6.5  3.0  5.5  1.8
o26      6.3  2.8  5.1  NaN
o27      6.1  2.7  5.6  1.5
o28      6.4  3.1  5.5  NaN
o29      6.0  2.9  4.8  1.6
o30      5.9  3.0  5.1  1.8

In [41]:
set_Um = set_C[set_C.isnull().values.any(axis=1)]
set_Uc=set_C[~set_C.isnull().values.any(axis=1)]
set_Um

A1   A2   A3   A4
Objects                    
o3       6.4  NaN  NaN  1.3
o6       6.3  2.8  4.9  NaN
o7       5.5  2.4  3.8  NaN
o8       NaN  2.7  4.0  1.4
o9       5.5  NaN  NaN  1.2
o13      5.5  NaN  4.4  1.4
o18      NaN  2.8  5.6  2.2
o26      6.3  2.8  5.1  NaN
o28      6.4  3.1  5.5  NaN

In [42]:
set_Uc

A1   A2   A3   A4
Objects                    
o1       5.9  3.2  4.8  2.0
o2       6.1  2.8  4.2  1.5
o4       6.4  2.5  4.3  1.4
o5       6.3  2.3  4.4  1.5
o10      6.0  2.8  4.5  1.4
o11      5.6  2.9  4.1  1.5
o12      5.5  2.5  4.0  1.5
o14      6.1  2.7  4.6  1.4
o15      5.8  2.6  4.0  1.4
o16      5.8  2.7  5.1  1.9
o17      5.7  2.5  5.0  2.0
o19      6.0  2.2  5.0  1.5
o20      5.6  2.8  4.9  2.0
o21      6.3  2.7  4.9  1.8
o22      6.2  2.8  4.8  1.8
o23      5.9  3.0  5.1  1.8
o24      6.4  2.8  5.6  2.1
o25      6.5  3.0  5.5  1.8
o27      6.1  2.7  5.6  1.5
o29      6.0  2.9  4.8  1.6
o30      5.9  3.0  5.1  1.8

In [43]:
def dis(Oi,Oj):
    diff=0
    for i in set_Um.columns:
        diff +=np.nansum(set_Um[i][Oi]-set_Uc[i][Oj])**2
    return np.sqrt(diff)
    
dis(0,1)

0.36055512754639946

In [44]:
dist=[]
for i in range(set_Um.shape[0]) :
    dist.append([])
    for j in range(set_Uc.shape[0]) :
        dist[i].append(dis(i,j))

In [45]:
Table =pd.DataFrame(dist,set_Um.index,set_Uc.index)
Table

Objects        o1        o2        o4        o5       o10       o11       o12  \
Objects                                                                         
o3       0.860233  0.360555  0.100000  0.223607  0.412311  0.824621  0.921954   
o6       0.574456  0.728011  0.678233  0.707107  0.500000  1.067708  1.240967   
o7       1.341641  0.824621  1.034408  1.004988  0.948683  0.591608  0.223607   
o8       1.118034  0.244949  0.360555  0.574456  0.509902  0.244949  0.223607   
o9       0.894427  0.670820  0.921954  0.854400  0.538516  0.316228  0.300000   
o13      0.824621  0.640312  0.905539  0.806226  0.509902  0.331662  0.412311   
o18      0.916515  1.565248  1.555635  1.476482  1.360147  1.658312  1.772005   
o26      0.640312  0.921954  0.860233  0.860233  0.670820  1.224745  1.392839   
o28      0.866025  1.367479  1.341641  1.363818  1.118034  1.624808  1.849324   

Objects       o14       o15       o16  ...       o19       o20       o21  \
Objects                                ...                                 
o3       0.316228  0.608276  0.848528  ...  0.447214  1.063015  0.509902   
o6       0.374166  1.048809  0.547723  ...  0.678233  0.700000  0.100000   
o7       1.044031  0.412311  1.367479  ...  1.315295  1.174734  1.392839   
o8       0.600000  0.100000  1.208305  ...  1.122497  1.086278  0.984886   
o9       0.632456  0.360555  0.761577  ...  0.583095  0.806226  1.000000   
o13      0.632456  0.500000  0.911043  ...  0.787401  0.787401  1.024695   
o18      1.284523  1.800000  0.591608  ...  1.100000  0.728011  0.812404   
o26      0.547723  1.224745  0.509902  ...  0.678233  0.728011  0.223607   
o28      1.029563  1.691153  0.824621  ...  1.104536  1.044031  0.728011   

Objects       o22       o23       o24       o25       o27       o29       o30  
Objects                                                                        
o3       0.538516  0.707107  0.800000  0.509902  0.360555  0.500000  0.707107  
o6       0.141421  0.489898  0.707107  0.663325  0.734847  0.331662  0.489898  
o7       1.284523  1.486607  2.051828  2.061553  1.920937  1.224745  1.486607  
o8       0.900000  1.208305  1.749286  1.581139  1.603122  0.848528  1.208305  
o9       0.921954  0.721110  1.272792  1.166190  0.670820  0.640312  0.721110  
o13      0.900000  0.900000  1.655295  1.539480  1.345362  0.670820  0.900000  
o18      0.894427  0.670820  0.100000  0.458258  0.707107  1.004988  0.670820  
o26      0.316228  0.447214  0.509902  0.489898  0.547723  0.435890  0.447214  
o28      0.787401  0.648074  0.316228  0.141421  0.509902  0.830662  0.648074  

[9 rows x 21 columns]

In [46]:
## determine the Kth nearset neighbors
def neighbor_Um(k):
    list_Index = set_Um.index.tolist()
    list_Index
    K_N=[]
    for i in list_Index:
          K_N.append(Table.loc[i].sort_values().head(k))
    return K_N
neighbor_Um(7)

[Objects
 o4     0.100000
 o5     0.223607
 o14    0.316228
 o2     0.360555
 o27    0.360555
 o10    0.412311
 o19    0.447214
 Name: o3, dtype: float64,
 Objects
 o21    0.100000
 o22    0.141421
 o29    0.331662
 o14    0.374166
 o30    0.489898
 o23    0.489898
 o10    0.500000
 Name: o6, dtype: float64,
 Objects
 o12    0.223607
 o15    0.412311
 o11    0.591608
 o2     0.824621
 o10    0.948683
 o5     1.004988
 o4     1.034408
 Name: o7, dtype: float64,
 Objects
 o15    0.100000
 o12    0.223607
 o11    0.244949
 o2     0.244949
 o4     0.360555
 o10    0.509902
 o5     0.574456
 Name: o8, dtype: float64,
 Objects
 o12    0.300000
 o11    0.316228
 o15    0.360555
 o10    0.538516
 o19    0.583095
 o14    0.632456
 o29    0.640312
 Name: o9, dtype: float64,
 Objects
 o11    0.331662
 o12    0.412311
 o15    0.500000
 o10    0.509902
 o14    0.632456
 o2     0.640312
 o29    0.670820
 Name: o13, dtype: float64,
 Objects
 o24    0.100000
 o25    0.458258
 o16    0.591608
 o30    0

In [47]:
##evaluat an object with k voisin with K_clusters
def evaluation (k,j,k_cluster):
    Nei_DF =pd.DataFrame(neighbor_Um(k))
    ev=[]
    C=0
    df1=cluster_map.set_index("data_index")
    for l in range(k_cluster):
        C=0
        for i in Nei_DF.loc[j].dropna().index:
            if df1.loc[i].loc["cluster"]== l: 
                    C+=1
        ev.append(C/k)
    return ev

##Determine the labels of clusters we have
def init_list_clusters(k_cluster):
    list_cluster=[]
    for j in range(k_cluster):
            list_cluster.append("C"+str(j))
    return list_cluster

##evaluate all the objects of Um with their neighbors's Clusters
def eval_all(k_cluster,k):
    list_objects=[]
    list_evaluation=[]
    list_cluster=[]
    list_Index = set_Um.index.tolist()
    list_Index
    for i in range(len(list_Index)):
        list_objects.append(list_Index[i])
        list_evaluation.append(evaluation(k,list_Index[i],k_cluster))
    df3 = pd.DataFrame(list_evaluation, index = list_objects, columns = init_list_clusters(k_cluster))
    return df3
eval_all(2,7)

C0        C1
o3   0.714286  0.285714
o6   0.285714  0.714286
o7   1.000000  0.000000
o8   1.000000  0.000000
o9   0.714286  0.285714
o13  0.857143  0.142857
o18  0.000000  1.000000
o26  0.000000  1.000000
o28  0.000000  1.000000

In [48]:
#determine if the objects are inside outside or partial a cluster
def three_way (alpha,beta,k_cluster,k):
    list1=[]
    i=0
    df = eval_all(k_cluster,k).T
    object_list=df.columns
    cluster_list=df.index.tolist()
    for c in cluster_list:
        inside=[]
        outside=[]
        partial=[]
        list1.append([])
        for o in object_list:
            if (df.loc[c][o]>=alpha):
                inside.append(o)
            elif (df.loc[c][o]<alpha and df.loc[c][o]>beta):
                partial.append(o)
            elif df.loc[c][o]<=beta:
                outside.append(o)
        list1[i].append(c)
        list1[i].append(inside)
        list1[i].append(outside)
        list1[i].append(partial)
        i=i+1
        df3 = pd.DataFrame(list1,columns=["cluster","Inside","Outside","Partial"])
        df3=df3.set_index('cluster')
    return df3

three_way(0.8,0.2,2,7)

Inside          Outside       Partial
cluster                                                
C0         [o7, o8, o13]  [o18, o26, o28]  [o3, o6, o9]
C1       [o18, o26, o28]    [o7, o8, o13]  [o3, o6, o9]

In [49]:
## utility, define the two players the accuracy and the generality
def Utility (alpha,beta,k_cluster,k):
    df1=cluster_map.set_index("data_index")
    df4 = eval_all(k_cluster,k).T
    object_list=df4.columns
    cluster_list=df4.index.tolist()
    df5 =three_way (alpha,beta,k_cluster,k)
    Totaly_clustred=0
    for i in cluster_list:
        Totaly_clustred += len(df5["Inside"].loc[i])
    correctly_Clustred=0
    for i in cluster_list:
        for j in df5["Inside"].loc[i]:
            if df1.loc[j].loc["cluster"]== int(i[1:]):
                correctly_Clustred+=1
    accuracy=correctly_Clustred/Totaly_clustred
    generality=Totaly_clustred/len(set_Um)
    return accuracy,generality
Utility(1,0,2,7)

(1.0, 0.5555555555555556)

In [50]:

# def payoff1(alpha,beta,alpha_,alpha__,beta_,beta__,k_cluster,k): 
#     #list of acc, and list of gen
#     list_Acc=[]
#     list_gen=[]
#     list_Acc.append([])
#     list_Acc[0].append(Utility ((alpha-alpha__),beta,k_cluster,k)[0])
#     list_Acc[0].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[0])
#     list_Acc[0].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[0])
#     list_Acc.append([])
#     list_Acc[1].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[0])
#     list_Acc[1].append(Utility ((alpha),(beta+beta__),k_cluster,k)[0])
#     list_Acc[1].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[0])
#     list_Acc.append([])
#     list_Acc[2].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[0])
#     list_Acc[2].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[0])
#     list_Acc[2].append(Utility ((alpha-alpha__),(beta+beta__),k_cluster,k)[0])
    
#     ##list of [acc,gen], and list of [alpha,beta] same index of each [acc,gen]
#     list_gen.append([])
#     list_gen[0].append(Utility ((alpha-alpha__),beta,k_cluster,k)[1])
#     list_gen[0].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[1])
#     list_gen[0].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[1])
#     list_gen.append([])
#     list_gen[1].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[1])
#     list_gen[1].append(Utility ((alpha),(beta+beta__),k_cluster,k)[1])
#     list_gen[1].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[1])
#     list_gen.append([])
#     list_gen[2].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[1])
#     list_gen[2].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[1])
#     list_gen[2].append(Utility ((alpha-alpha__),(beta+beta__),k_cluster,k)[1])
    
    
    
#     set_PAYOFF=[] 
#     set_alphabeta=[]
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[0].append(alpha-alpha__)
#     set_alphabeta[0].append(beta)
#     set_PAYOFF[0].append(Utility ((alpha-alpha__),beta,k_cluster,k)[0])
#     set_PAYOFF[0].append(Utility ((alpha-alpha__),beta,k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[1].append((alpha-alpha_))
#     set_alphabeta[1].append((beta+beta_))
#     set_PAYOFF[1].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[0])
#     set_PAYOFF[1].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[2].append((alpha-alpha__))
#     set_alphabeta[2].append((beta+beta_))
#     set_PAYOFF[2].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[0])
#     set_PAYOFF[2].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[3].append((alpha-alpha_))
#     set_alphabeta[3].append((beta+beta_))
#     set_PAYOFF[3].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[0])
#     set_PAYOFF[3].append(Utility ((alpha-alpha_),(beta+beta_),k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[4].append((alpha))
#     set_alphabeta[4].append((beta+beta__))
#     set_PAYOFF[4].append(Utility ((alpha),(beta+beta__),k_cluster,k)[0])
#     set_PAYOFF[4].append(Utility ((alpha),(beta+beta__),k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[5].append((alpha-alpha_))
#     set_alphabeta[5].append((beta+beta__))
#     set_PAYOFF[5].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[0])
#     set_PAYOFF[5].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[6].append((alpha-alpha__))
#     set_alphabeta[6].append((beta+beta_))
#     set_PAYOFF[6].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[0])
#     set_PAYOFF[6].append(Utility ((alpha-alpha__),(beta+beta_),k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[7].append((alpha-alpha__))
#     set_alphabeta[7].append((beta+beta_))
#     set_PAYOFF[7].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[0])
#     set_PAYOFF[7].append(Utility ((alpha-alpha_),(beta+beta__),k_cluster,k)[1])
#     set_PAYOFF.append([])
#     set_alphabeta.append([])
#     set_alphabeta[8].append((alpha-alpha__))
#     set_alphabeta[8].append((beta+beta__))
#     set_PAYOFF[8].append(Utility ((alpha-alpha__),(beta+beta__),k_cluster,k)[0])
#     set_PAYOFF[8].append(Utility ((alpha-alpha__),(beta+beta__),k_cluster,k)[1])


#     return set_PAYOFF,set_alphabeta,list_Acc,list_gen
# list_12= payoff1(1,0,0.05,0.1,0.05,0.1,2,7) 
# df7 = pd.DataFrame(list_12[0],columns=["Accuracy","Generality"])
# list_12[2]

In [51]:

def payoff1(alpha,beta,alpha_,alpha__,beta_,beta__,k_cluster,k): 
    #list of acc, and list of gen
    list_Acc=[]
    list_gen=[]
    list_Acc.append([])
    list_Acc[0].append(Utility ((alpha__),beta,k_cluster,k)[0])
    list_Acc[0].append(Utility ((alpha_),(beta_),k_cluster,k)[0])
    list_Acc[0].append(Utility ((alpha__),(beta_),k_cluster,k)[0])
    list_Acc.append([])
    list_Acc[1].append(Utility ((alpha_),(beta_),k_cluster,k)[0])
    list_Acc[1].append(Utility ((alpha),(beta__),k_cluster,k)[0])
    list_Acc[1].append(Utility ((alpha_),(beta__),k_cluster,k)[0])
    list_Acc.append([])
    list_Acc[2].append(Utility ((alpha__),(beta_),k_cluster,k)[0])
    list_Acc[2].append(Utility ((alpha_),(beta__),k_cluster,k)[0])
    list_Acc[2].append(Utility ((alpha__),(beta__),k_cluster,k)[0])
    
    ##list of [acc,gen], and list of [alpha,beta] same index of each [acc,gen]
    list_gen.append([])
    list_gen[0].append(Utility ((alpha__),beta,k_cluster,k)[1])
    list_gen[0].append(Utility ((alpha_),(beta_),k_cluster,k)[1])
    list_gen[0].append(Utility ((alpha__),(beta_),k_cluster,k)[1])
    list_gen.append([])
    list_gen[1].append(Utility ((alpha_),(beta_),k_cluster,k)[1])
    list_gen[1].append(Utility ((alpha),(beta__),k_cluster,k)[1])
    list_gen[1].append(Utility ((alpha_),(beta__),k_cluster,k)[1])
    list_gen.append([])
    list_gen[2].append(Utility ((alpha__),(beta_),k_cluster,k)[1])
    list_gen[2].append(Utility ((alpha_),(beta__),k_cluster,k)[1])
    list_gen[2].append(Utility ((alpha__),(beta__),k_cluster,k)[1])
    
    
    
    set_PAYOFF=[] 
    set_alphabeta=[]
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[0].append(alpha__)
    set_alphabeta[0].append(beta)
    set_PAYOFF[0].append(Utility ((alpha__),beta,k_cluster,k)[0])
    set_PAYOFF[0].append(Utility ((alpha__),beta,k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[1].append((alpha_))
    set_alphabeta[1].append((beta_))
    set_PAYOFF[1].append(Utility ((alpha_),(beta_),k_cluster,k)[0])
    set_PAYOFF[1].append(Utility ((alpha_),(beta_),k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[2].append((alpha__))
    set_alphabeta[2].append((beta_))
    set_PAYOFF[2].append(Utility ((alpha__),(beta_),k_cluster,k)[0])
    set_PAYOFF[2].append(Utility ((alpha__),(beta_),k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[3].append((alpha_))
    set_alphabeta[3].append((beta_))
    set_PAYOFF[3].append(Utility ((alpha_),(beta_),k_cluster,k)[0])
    set_PAYOFF[3].append(Utility ((alpha_),(beta_),k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[4].append((alpha))
    set_alphabeta[4].append((beta__))
    set_PAYOFF[4].append(Utility ((alpha),(beta__),k_cluster,k)[0])
    set_PAYOFF[4].append(Utility ((alpha),(beta__),k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[5].append((alpha_))
    set_alphabeta[5].append((beta__))
    set_PAYOFF[5].append(Utility ((alpha_),(beta__),k_cluster,k)[0])
    set_PAYOFF[5].append(Utility ((alpha_),(beta__),k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[6].append((alpha__))
    set_alphabeta[6].append((beta_))
    set_PAYOFF[6].append(Utility ((alpha__),(beta_),k_cluster,k)[0])
    set_PAYOFF[6].append(Utility ((alpha__),(beta_),k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[7].append((alpha__))
    set_alphabeta[7].append((beta_))
    set_PAYOFF[7].append(Utility ((alpha_),(beta__),k_cluster,k)[0])
    set_PAYOFF[7].append(Utility ((alpha_),(beta__),k_cluster,k)[1])
    set_PAYOFF.append([])
    set_alphabeta.append([])
    set_alphabeta[8].append((alpha__))
    set_alphabeta[8].append((beta__))
    set_PAYOFF[8].append(Utility ((alpha__),(beta__),k_cluster,k)[0])
    set_PAYOFF[8].append(Utility ((alpha__),(beta__),k_cluster,k)[1])


    return set_PAYOFF,set_alphabeta,list_Acc,list_gen
list_12= payoff1(1,0,0.65,0.6,0.35,0.4,2,7) 
df7 = pd.DataFrame(list_12[0],columns=["Accuracy","Generality"])
df7

Accuracy  Generality
0       1.0    1.000000
1       1.0    1.000000
2       1.0    1.000000
3       1.0    1.000000
4       1.0    0.555556
5       1.0    1.000000
6       1.0    1.000000
7       1.0    1.000000
8       1.0    1.000000

In [52]:
list_12[0]

[[1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 0.5555555555555556],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0]]

In [53]:
import nashpy as nash
import numpy as np
# Create the game with the payoff matrix
A =payoff1(1,0,0.05,0.1,0.05,0.1,2,7)[2] # A is the row player
B = payoff1(1,0,0.05,0.1,0.05,0.1,2,7)[3] # B is the column player
game1 = nash.Game(A,B)
game1
# Find the Nash Equilibrium with Support Enumeration
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0., 0.]), array([1., 0., 0.]))
(array([1., 0., 0.]), array([0., 0., 1.]))
(array([0., 1., 0.]), array([1., 0., 0.]))
(array([0., 1., 0.]), array([0., 0., 1.]))
(array([0., 0., 1.]), array([1., 0., 0.]))
(array([0., 0., 1.]), array([0., 0., 1.]))


C:\Users\houss\anaconda3\lib\site-packages\nashpy\algorithms\support_enumeration.py:259: RuntimeWarning: 
An even number of (6) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


In [54]:
sigma_r = eq[0].tolist()
sigma_c = eq[1].tolist()
game1[sigma_r, sigma_c]
game1

Bi matrix game with payoff matrices:

Row player:
[[0.69230769 0.69230769 0.69230769]
 [0.69230769 1.         0.69230769]
 [0.69230769 0.69230769 0.69230769]]

Column player:
[[1.44444444 1.44444444 1.44444444]
 [1.44444444 0.55555556 1.44444444]
 [1.44444444 1.44444444 1.44444444]]

In [55]:
a,b=game1[sigma_r, sigma_c]
print(a, b)

0.6923076923076923 1.4444444444444444


In [62]:
import nashpy as nash
import numpy as np
accuracy=1
generality=0
max_iteration=15
set_PAYOFF=[]
set_alpha_beta=[]
alpha_=0.9
alpha__=0.85
beta_=0.1
beta__=0.15


def payoff(alpha,beta,alpha_,alpha__,beta_,beta__,k_cluster,k): 
    i=0
    accuracy=1
    generality=0
    iteration=0
    set_PAYOFF=[]
    set_PAYOFF_max=[]
    set_alpha_beta=[]
    set_alpha_beta_of_max=[]
    max_iteration=25
    while (accuracy > generality and alpha > 0.5 and beta < 0.5 and iteration<max_iteration):
        iteration=iteration+1
# Create the game with the payoff matrix
        list_12=payoff1(alpha,beta,alpha_,alpha__,beta_,beta__,k_cluster,k)
        
        A =list_12[2] # A is the row player
        B = list_12[3] # B is the column player
        game1 = nash.Game(A,B)
        
        # Find the Nash Equilibrium with Support Enumeration
        equilibria = game1.support_enumeration()
        for eq in equilibria:
            b=eq
        sigma_r = eq[0].tolist()
        sigma_c = eq[1].tolist()
        game1[sigma_r, sigma_c]
        accuracy,generality =game1[sigma_r, sigma_c]
#         list_12[0].reverse()
#         index = list_12[0].index([a, b])
#         # printing the final index
#         index_of_alphaBeta= len(list_12[0]) - index - 1
        
        
#         alpha1=list_12[1][index_of_alphaBeta][0]
#         beta1=list_12[1][index_of_alphaBeta][1]
        
         #changement de valeurs de alpha et beta 
        ia=b[0].tolist().index(1)
        ib=b[1].tolist().index(1)
        a,c=["alpha_","betaplus","alpha_betaplus"][ia],["alpha_","betaplus","alpha_betaplus"][ib]
#alpha,beta,alpha_,alpha__,betaplus,betaplus2,
        if a=="alpha_" and c=="alpha_":
            alpha1 = alpha__
            beta1 = beta
        if a=="alpha_" and c=="betaplus":
            alpha1 =alpha_
            beta1 = beta_
        if a=="alpha_" and c=="alpha_betaplus":
            alpha1 = alpha__
            beta1 = beta_
        if a=="betaplus" and c=="alpha_":
            alpha1 = alpha_
            beta1 = beta_
        if a=="betaplus" and c=="betaplus":
            alpha1 = alpha
            beta1 = beta__
        if a=="betaplus" and c=="alpha_betaplus":
            alpha1 =alpha_
            beta1 =beta__
        if a=="alpha_betaplus" and c=="alpha_":
            alpha1 = alpha__
            beta1 = beta_
        if a=="alpha_betaplus" and c=="betaplus":
            alpha1 = alpha_
            beta1 = beta__
        if a=="alpha_betaplus" and c=="alpha_betaplus":
            alpha1 =alpha__
            beta1 = beta__
        #calcul alpha_, alpha__, betaplus, betaplus2
        c =1.5
#         alpha_=alpha*0.05
#         alpha__=alpha*0.1
#         beta_=beta*0.05
#         beta__=beta*0.1
        alpha_ = alpha - ( alpha*Utility (alpha1,beta1,k_cluster,k)[1]-Utility (alpha,beta,k_cluster,k)[1])
        alpha__ = alpha - c*( alpha*Utility (alpha1,beta1,k_cluster,k)[1]-Utility (alpha,beta,k_cluster,k)[1])
        beta_ = beta - (beta*Utility (alpha1,beta1,k_cluster,k)[1]-Utility (alpha,beta,k_cluster,k)[1])
        beta__ = beta - c*(beta*Utility (alpha1,beta1,k_cluster,k)[1]-Utility (alpha,beta,k_cluster,k)[1])
        #         set_alpha_beta.append([])
#         set_alpha_beta[i].append(alpha)
#         set_alpha_beta[i].append(beta)
        alpha0=alpha
        beta0=beta
        
        alpha=alpha1
        beta=beta1
#         set_PAYOFF.append([])
#         set_PAYOFF[i].append(Utility ((alpha-alpha_),beta,k_cluster,k)[0])
#         set_PAYOFF[i].append(Utility ((alpha-alpha_),beta,k_cluster,k)[1])
#         max_acc=set_PAYOFF[0][0]
#         max_gen=set_PAYOFF[0][1]
#         set_Best=[]
#         for i in range(len(set_PAYOFF)):
#             if set_PAYOFF[i][0]>=set_PAYOFF[0][0] and  set_PAYOFF[i][1]>=set_PAYOFF[0][1]:
#                 set_PAYOFF_max=set_PAYOFF[i]
#                 set_alpha_beta_of_max=set_alpha_beta[i]
#         alpha=alpha-alpha_
#         i=i+1
#         iteration=iteration+1    
    return alpha,beta,list_12[0]
# list_12= payoff(1,0,alpha_,alpha__,beta_,beta__,2,7) 
# df7 = pd.DataFrame(list_12[0],columns=["Accuracy","Generality"])
# df7.set_index([list_12[1]])
payoff(1,0,alpha_,alpha__,beta_,beta__,2,7) 

(0.8333333333333335,
 0.8333333333333334,
 [[1.0, 0.6666666666666666],
  [1.0, 0.5555555555555556],
  [1.0, 0.6666666666666666],
  [1.0, 0.5555555555555556],
  [1.0, 0.6666666666666666],
  [1.0, 0.5555555555555556],
  [1.0, 0.6666666666666666],
  [1.0, 0.5555555555555556],
  [1.0, 0.6666666666666666]])

In [57]:
def GTRS(alpha,beta,alpha_,alpha__,beta_,beta__,k_neighbors,k_cluster):
    return None

In [58]:
def dis(Oi,Oj):
    diff=0
    for i in set_Um.columns:
        diff +=np.nansum(set_Um[i][Oi]-set_Uc[i][Oj])**2
    return np.sqrt(diff)
    
dis(0,1)

dist=[]
for i in range(set_Um.shape[0]) :
    dist.append([])
    for j in range(set_Uc.shape[0]) :
        dist[i].append(dis(i,j))